# Generated by Django 2.1.7 on 2019-04-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvasX', '0003_auto_20190422_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
