# Generated by Django 2.1.7 on 2019-04-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvasX', '0004_auto_20190422_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
