# Generated by Django 2.1.7 on 2019-04-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvasX', '0005_auto_20190422_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='zipcode',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
