# Generated by Django 2.1.7 on 2019-04-22 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canvasX', '0007_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prof_teams',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_no', models.IntegerField()),
                ('section_type', models.CharField(max_length=10)),
                ('limit', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvasX.Course')),
                ('prof_team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvasX.Prof_teams')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course_id', 'sec_no')},
        ),
    ]
