# Generated by Django 2.1.7 on 2019-04-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvasX', '0008_auto_20190422_1955'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
            ],
        ),
    ]
