# Generated by Django 2.1.7 on 2019-04-22 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canvasX', '0009_auto_20190422_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_no', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvasX.Course')),
                ('student_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvasX.Student')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='enrolls',
            unique_together={('student_email', 'course_id', 'section_no')},
        ),
    ]
