# Generated by Django 2.1.7 on 2019-04-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvasX', '0010_auto_20190422_2048'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrolls',
            unique_together={('student_email', 'course_id')},
        ),
    ]
