# Generated by Django 2.1.7 on 2019-04-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvasX', '0012_auto_20190422_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_student',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
