# Generated by Django 2.1.7 on 2019-04-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvasX', '0014_auto_20190424_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('dept_name', models.CharField(max_length=50)),
                ('dept_head', models.CharField(max_length=50)),
            ],
        ),
    ]
