# Generated by Django 2.1.7 on 2019-04-24 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canvasX', '0016_auto_20190424_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_no', models.IntegerField()),
                ('hw_no', models.IntegerField()),
                ('hw_detail', models.CharField(max_length=200)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvasX.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Homework_grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_no', models.IntegerField()),
                ('hw_no', models.IntegerField()),
                ('grades', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvasX.Course')),
                ('student_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvasX.Student')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='homework_grades',
            unique_together={('student_email', 'course_id', 'sec_no', 'hw_no')},
        ),
        migrations.AlterUniqueTogether(
            name='homework',
            unique_together={('course_id', 'sec_no', 'hw_no')},
        ),
    ]
