# Generated by Django 2.2 on 2019-04-25 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canvasX', '0018_auto_20190425_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capstone_setion',
            fields=[
                ('sec_no', models.IntegerField()),
                ('project_no', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvasX.Course')),
                ('sponsor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvasX.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Capstone_Team_Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvasX.Course')),
                ('project_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvasX.Capstone_setion')),
                ('student_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvasX.Student')),
            ],
            options={
                'unique_together': {('student_email', 'team_id', 'course_id', 'project_no')},
            },
        ),
        migrations.CreateModel(
            name='Capstone_Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_no', models.IntegerField(null=True)),
                ('team_id', models.IntegerField(null=True, unique=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvasX.Course')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvasX.Capstone_setion')),
            ],
            options={
                'unique_together': {('course_id', 'sec_no', 'team_id')},
            },
        ),
        migrations.CreateModel(
            name='Capstone_grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_no', models.IntegerField()),
                ('team_id', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvasX.Course')),
            ],
            options={
                'unique_together': {('team_id', 'course_id', 'sec_no')},
            },
        ),
    ]
